### ISSUE TITLE
Time out when adding whitelist

### ISSUE THREAD

**Issue by zlu93311** [openthread/openthread#269]
Tested on Linux with simulator.  The OpenThread Cert tests failed with timeout when nodes add WhiteList.   Python version 3.2.2.

====================================================
bash-4.2$ python Cert_5_1_02_ChildAddressTimeout.py
./ot-cli 1
1 : whitelist clear
1 : whitelist disable
1 : childtimeout 100
./ot-cli 2
2 : whitelist clear
2 : whitelist disable
2 : childtimeout 100
./ot-cli 3
3 : whitelist clear
3 : whitelist disable
3 : childtimeout 100
./ot-cli 4
4 : whitelist clear
4 : whitelist disable
4 : childtimeout 100
1 : panid 64206
1 : mode rsdn
2 : extaddr
1 : whitelist add b'e2b3540590b0fd87'
E
======================================================================
ERROR: test (__main__.Cert_5_1_02_ChildAddressTimeout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zigbee_lab/tools/python/lib/python3.3/site-packages/pexpect/__init__.py", line 1535, in expect_loop
    c = self.read_nonblocking(self.maxread, timeout)
  File "/zigbee_lab/tools/python/lib/python3.3/site-packages/pexpect/__init__.py", line 968, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Cert_5_1_02_ChildAddressTimeout.py", line 49, in setUp
    self.nodes[LEADER].add_whitelist(self.nodes[ROUTER].get_addr64())
  File "/home/zjlu/work/openthread/tests/scripts/thread-cert/node.py", line 121, in add_whitelist
    self.pexpect.expect('Done')
  File "/zigbee_lab/tools/python/lib/python3.3/site-packages/pexpect/__init__.py", line 1451, in expect
    timeout, searchwindowsize)
  File "/zigbee_lab/tools/python/lib/python3.3/site-packages/pexpect/__init__.py", line 1466, in expect_list
    timeout, searchwindowsize)
  File "/zigbee_lab/tools/python/lib/python3.3/site-packages/pexpect/__init__.py", line 1568, in expect_loop
    raise TIMEOUT(str(err) + '\n' + str(self))
pexpect.TIMEOUT: Timeout exceeded.
<pexpect.spawn object at 0x2b3ed099bd10>
version: 3.3
command: ./ot-cli
args: ['./ot-cli', '1']
searcher: <pexpect.searcher_re object at 0x2b3ed099be50>
buffer (last 100 chars): b"\r\n> whitelist add b'e2b3540590b0fd87'\r\nError 6\r\n> "
before (last 100 chars): b"\r\n> whitelist add b'e2b3540590b0fd87'\r\nError 6\r\n> "
after: <class 'pexpect.TIMEOUT'>
=====================================================

**Comment by jwhui** [comment]
Turns out only minimal changes are needed to support both python2 and python3.  I just submitted #270.  Let me know if this fixes your issue.
