### ISSUE TITLE
[nrf52840] Hardfault on COAP header init

### ISSUE THREAD

**Issue by nealjack** [openthread/openthread#3369]
**Describe the bug**
Upon attempting to initialize a COAP header, a hardfault occurs at the [memset of mOption](https://github.com/openthread/openthread/blob/master/src/core/coap/coap_header.cpp#L52).

**To Reproduce**
Using edb7982 with an nRF52840 built with:
```
make -f examples/Makefile-nrf52840 COMMISSIONER=1 JOINER=1 COAP=1 DNS_CLIENT=1 MTD_NETDIAG=1 BORDER_ROUTER=1 MAC_FILTER=1 UDP_PROXY=1 DHCP6_SERVER=1 DHCP6_CLIENT=1 DNS_SERVER=1 DISABLE_SPI=1
```
and manually copied to overwrite the Openthread libraries in the nRF5 SDK for Thread v2.0.0.

The network is comprised of 3 routers based on the nRF52840 dongle, two sleepy end devices and a Raspberry Pi Border Router.

**Expected behavior**
My application, when built against the [thread-reference-20180926 tag](https://github.com/openthread/openthread/tree/thread-reference-20180926) successfully initializes the header and sends a COAP message.

**Console/log output**
RTT trace of hardfault:
```
<info> app: Thread version: OPENTHREAD/20170716-01135-gedb7982f; NRF52840; Dec 11 2018 22:05:35
<info> app: Network name:   OpenThread
<info> app: Thread Channel: 11
<info> app: TX Power: 0 dBm
<info> app: Thread PANID: 0xFACE
<info> app: Thread interface has been enabled.
<info> app: 802.15.4 Channel: 11
<info> app: 802.15.4 PAN ID:  0xFACE
<info> app: rx-on-when-idle:  disabled
<info> app: State changed! Flags: 0x040F133D Current role: 1

<info> app: State changed! Flags: 0x00000040 Current role: 1

<error> hardfault: HARD FAULT at 0x000040AA
<error> hardfault:   R0:  0x2003FED8  R1:  0x00000000  R2:  0x00000200  R3:  0x20000A64
<error> hardfault:   R12: 0x2000AE80  LR:  0x000040C9  PSR: 0x21070021
<error> hardfault: Cause: Data bus error (return address in the stack frame is not related to the instruction that caused the error).
```
GDB backtrace:
```
#0  0x00000c08 in HardFault_c_handler ()
#1  <signal handler called>
#2  ot::Coap::Header::Init (this=this@entry=0x2003fed8)
    at /openthread/examples/../src/core/coap/coap_header.cpp:52
#3  0x000040c8 in ot::Coap::Header::Init (this=0x2003fed8, 
    aType=<optimized out>, aCode=<optimized out>)
    at /openthread/examples/../src/core/coap/coap_header.cpp:59
#4  0x00002f20 in thread_coap_send ()
#5  0x000002dc in send_timer_callback ()
#6  0x00000668 in RTC1_IRQHandler ()
#7  <signal handler called>
#8  0x00002e5a in thread_sleep ()
#9  0x000003b2 in main ()
```

**Comment by nealjack** [comment]
Yup, that was it. Thanks for the quick reply!
