### ISSUE TITLE
Thread 1.2 CI tests failing intermittently

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#5035]
One example failure.

Full log archive:[logs_5690.zip](https://github.com/openthread/openthread/files/4712216/logs_5690.zip)

Log snippet:
```
2020-06-01T11:10:14.8939405Z [0;32mPASS[0m tests/scripts/thread-cert/v1_2_router_5_1_1.py
2020-06-01T11:10:28.4440134Z [0;31mFAIL[0m tests/scripts/thread-cert/v1_2_test_backbone_router_service.py
2020-06-01T11:10:35.3514948Z [0;32mPASS[0m tests/scripts/thread-cert/v1_2_test_enhanced_frame_pending.py
2020-06-01T11:10:38.9106973Z [0;32mPASS[0m tests/scripts/thread-cert/v1_2_test_enhanced_keep_alive.py
2020-06-01T11:10:39.9034116Z [0;32mPASS[0m tests/scripts/thread-cert/v1_2_test_multicast_registration.py
2020-06-01T11:10:40.7276915Z [0;32mPASS[0m tests/scripts/thread-cert/v1_2_test_parent_selection.py
2020-06-01T11:10:40.7277565Z ==================================
2020-06-01T11:10:40.7277823Z          Test Summary
2020-06-01T11:10:40.7278089Z ==================================
2020-06-01T11:10:40.7278342Z # TOTAL: 6
2020-06-01T11:10:40.7278583Z # PASS: 5
2020-06-01T11:10:40.7279049Z # FAIL: 1
2020-06-01T11:10:40.7290263Z ==============================
2020-06-01T11:10:40.7290879Z !!! FAIL:tests/scripts/thread-cert/v1_2_test_backbone_router_service.py
2020-06-01T11:10:40.7291138Z ==============================
2020-06-01T11:10:40.7291510Z /home/runner/work/openthread/openthread/build/cmake/openthread-simulation-1.1/examples/apps/cli/ot-cli-ftd 1
2020-06-01T11:10:40.7291635Z 1: extpanid 000db80000000000
2020-06-01T11:10:40.7291746Z 1: panid 64206
2020-06-01T11:10:40.7291847Z 1: mode rsdn
2020-06-01T11:10:40.7292194Z /home/runner/work/openthread/openthread/build/cmake/openthread-simulation-1.2-bbr/examples/apps/cli/ot-cli-ftd 2
2020-06-01T11:10:40.7292301Z 2: extpanid 000db80000000000
2020-06-01T11:10:40.7292717Z 2: panid 64206
2020-06-01T11:10:40.7292826Z 2: mode rsdn
2020-06-01T11:10:40.7293228Z /home/runner/work/openthread/openthread/build/cmake/openthread-simulation-1.2-bbr/examples/apps/cli/ot-cli-ftd 3
2020-06-01T11:10:40.7293334Z 3: extpanid 000db80000000000
2020-06-01T11:10:40.7293436Z 3: panid 64206
2020-06-01T11:10:40.7293534Z 3: mode rsdn
2020-06-01T11:10:40.7293632Z 2: extaddr
2020-06-01T11:10:40.7293722Z 1: macfilter addr add 560b4cb4225a9d9e
2020-06-01T11:10:40.7293825Z 3: extaddr
2020-06-01T11:10:40.7293924Z 1: macfilter addr add 06768772f283500b
2020-06-01T11:10:40.7294029Z 1: macfilter addr whitelist
2020-06-01T11:10:40.7294110Z 1: extaddr
2020-06-01T11:10:40.7294209Z 2: macfilter addr add 968f2bec0e5fbfe1
2020-06-01T11:10:40.7294309Z 3: extaddr
2020-06-01T11:10:40.7294408Z 2: macfilter addr add 06768772f283500b
2020-06-01T11:10:40.7294495Z 2: macfilter addr whitelist
2020-06-01T11:10:40.7294595Z 1: extaddr
2020-06-01T11:10:40.7294693Z 3: macfilter addr add 968f2bec0e5fbfe1
2020-06-01T11:10:40.7294801Z 2: extaddr
2020-06-01T11:10:40.7294882Z 3: macfilter addr add 560b4cb4225a9d9e
2020-06-01T11:10:40.7294985Z 3: macfilter addr whitelist
2020-06-01T11:10:40.7295086Z 1: ifconfig up
2020-06-01T11:10:40.7295184Z 1: thread start
2020-06-01T11:10:40.7295265Z 1: state
2020-06-01T11:10:40.7295365Z 2: routerselectionjitter 1
2020-06-01T11:10:40.7295466Z 2: bbr jitter 5
2020-06-01T11:10:40.7295884Z 2: bbr config seqno 1
2020-06-01T11:10:40.7295966Z 2: ifconfig up
2020-06-01T11:10:40.7296066Z 2: thread start
2020-06-01T11:10:40.7296173Z ActiveOperationalDataset is not implemented yet.
2020-06-01T11:10:40.7296279Z 2: state
2020-06-01T11:10:40.7296361Z 2: bbr enable
2020-06-01T11:10:40.7296462Z 2: bbr state
2020-06-01T11:10:40.7296562Z 2: ipmaddr
2020-06-01T11:10:40.7296661Z 2: ipmaddr
2020-06-01T11:10:40.7297645Z 2: prefix add fd00:7d03:7d03:7d03::/64 prosD med
2020-06-01T11:10:40.7297768Z 2: netdataregister
2020-06-01T11:10:40.7297866Z 2: ipmaddr
2020-06-01T11:10:40.7297945Z 2: reset
2020-06-01T11:10:40.7298236Z 2: bbr jitter 5
2020-06-01T11:10:40.7298354Z 2: routerselectionjitter 1
2020-06-01T11:10:40.7298601Z 2: prefix add fd00:7d03:7d03:7d03::/64 prosD med
2020-06-01T11:10:40.7298687Z 2: netdataregister
2020-06-01T11:10:40.7298789Z 2: bbr enable
2020-06-01T11:10:40.7298889Z 2: ifconfig up
2020-06-01T11:10:40.7298986Z 2: thread start
2020-06-01T11:10:40.7299066Z 2: state
2020-06-01T11:10:40.7299169Z 2: bbr state
2020-06-01T11:10:40.7299268Z 2: bbr config
2020-06-01T11:10:40.7299366Z 2: reset
2020-06-01T11:10:40.7299447Z 2: routerselectionjitter 1
2020-06-01T11:10:40.7299552Z 2: bbr jitter 5
2020-06-01T11:10:40.7299659Z 2: prefix add fd00:7d03:7d03:7d03::/64 prosD med
2020-06-01T11:10:40.7299764Z 2: netdataregister
2020-06-01T11:10:40.7299844Z 2: bbr enable
2020-06-01T11:10:40.7299943Z 2: ifconfig up
2020-06-01T11:10:40.7300040Z 2: thread start
2020-06-01T11:10:40.7300138Z 2: state
2020-06-01T11:10:40.7300218Z 2: bbr state
2020-06-01T11:10:40.7300316Z 2: bbr config
2020-06-01T11:10:40.7300417Z 3: routerselectionjitter 1
2020-06-01T11:10:40.7300524Z 3: bbr jitter 5
2020-06-01T11:10:40.7300610Z 3: prefix add fd00:7d03:7d03:7d03::/64 prosD med
2020-06-01T11:10:40.7300714Z 3: netdataregister
2020-06-01T11:10:40.7300811Z 3: ifconfig up
2020-06-01T11:10:40.7300908Z 3: thread start
2020-06-01T11:10:40.7300992Z ActiveOperationalDataset is not implemented yet.
2020-06-01T11:10:40.7301095Z 3: state
2020-06-01T11:10:40.7301199Z 3: bbr state
2020-06-01T11:10:40.7301276Z 3: ipmaddr
2020-06-01T11:10:40.7301376Z 3: ipmaddr
2020-06-01T11:10:40.7301482Z 3: prefix remove fd00:7d03:7d03:7d03::/64
2020-06-01T11:10:40.7301591Z 3: netdataregister
2020-06-01T11:10:40.7301670Z 3: bbr enable
2020-06-01T11:10:40.7301770Z 3: bbr config seqno 255
2020-06-01T11:10:40.7301872Z 3: bbr state
2020-06-01T11:10:40.7301970Z 3: bbr register
2020-06-01T11:10:40.7302049Z 3: bbr state
2020-06-01T11:10:40.7302148Z 2: bbr state
2020-06-01T11:10:40.7302246Z 2: bbr config
2020-06-01T11:10:40.7302345Z 3: ipaddr
2020-06-01T11:10:40.7302434Z 2: ping fd00:7d03:7d03:7d03:7f4b:5bcc:bd81:feeb
2020-06-01T11:10:40.7302544Z 3: reset
2020-06-01T11:10:40.7302644Z 3: rloc16
2020-06-01T11:10:40.7302743Z 1: releaserouterid 12
2020-06-01T11:10:40.7302824Z 2: bbr state
2020-06-01T11:10:40.7302925Z 3: routerselectionjitter 1
2020-06-01T11:10:40.7303025Z 3: bbr jitter 5
2020-06-01T11:10:40.7303131Z 2: prefix add fd00:7d03:7d03:7d03::/64 prosD med
2020-06-01T11:10:40.7303222Z 2: netdataregister
2020-06-01T11:10:40.7303322Z 3: bbr enable
2020-06-01T11:10:40.7303421Z 3: ifconfig up
2020-06-01T11:10:40.7303521Z 3: thread start
2020-06-01T11:10:40.7303603Z 3: state
2020-06-01T11:10:40.7303704Z 3: bbr state
2020-06-01T11:10:40.7303802Z 2: ipmaddr
2020-06-01T11:10:40.7303901Z 2: ipmaddr
2020-06-01T11:10:40.7303979Z 3: ipaddr
2020-06-01T11:10:40.7304083Z 2: ping fd00:7d03:7d03:7d03:7f4b:5bcc:bd81:feeb
2020-06-01T11:10:40.7304188Z 1: thread stop
2020-06-01T11:10:40.7304266Z 1: ifconfig down
2020-06-01T11:10:40.7304413Z 1: exit
2020-06-01T11:10:40.7304514Z 2: thread stop
2020-06-01T11:10:40.7304617Z 2: ifconfig down
2020-06-01T11:10:40.7304699Z E
2020-06-01T11:10:40.7304805Z ======================================================================
2020-06-01T11:10:40.7304918Z ERROR: test (__main__.TestBackboneRouterService)
2020-06-01T11:10:40.7305362Z ----------------------------------------------------------------------
2020-06-01T11:10:40.7305459Z Traceback (most recent call last):
2020-06-01T11:10:40.7306010Z   File "/home/runner/work/openthread/openthread/tests/scripts/thread-cert/thread_cert.py", line 164, in tearDown
2020-06-01T11:10:40.7306144Z     node.destroy()
2020-06-01T11:10:40.7306467Z   File "/home/runner/work/openthread/openthread/tests/scripts/thread-cert/node.py", line 303, in destroy
2020-06-01T11:10:40.7306590Z     self.pexpect.expect(pexpect.EOF)
2020-06-01T11:10:40.7306890Z   File "/home/runner/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 344, in expect
2020-06-01T11:10:40.7307010Z     timeout, searchwindowsize, async_)
2020-06-01T11:10:40.7307430Z   File "/home/runner/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 372, in expect_list
2020-06-01T11:10:40.7307567Z     return exp.expect_loop(timeout)
2020-06-01T11:10:40.7307902Z   File "/home/runner/.local/lib/python3.6/site-packages/pexpect/expect.py", line 181, in expect_loop
2020-06-01T11:10:40.7308029Z     return self.timeout(e)
2020-06-01T11:10:40.7308346Z   File "/home/runner/.local/lib/python3.6/site-packages/pexpect/expect.py", line 144, in timeout
2020-06-01T11:10:40.7308475Z     raise exc
2020-06-01T11:10:40.7308588Z pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f31797f0080>
2020-06-01T11:10:40.7308688Z searcher: searcher_re:
2020-06-01T11:10:40.7308791Z     0: EOF
2020-06-01T11:10:40.7308897Z <pexpect.popen_spawn.PopenSpawn object at 0x7f31797f0080>
2020-06-01T11:10:40.7309008Z searcher: searcher_re:
2020-06-01T11:10:40.7309090Z     0: EOF
2020-06-01T11:10:40.7309155Z 
2020-06-01T11:10:40.7309426Z ----------------------------------------------------------------------
2020-06-01T11:10:40.7309581Z Ran 1 test in 5.043s
2020-06-01T11:10:40.7309649Z 
2020-06-01T11:10:40.7309727Z FAILED (errors=1)
2020-06-01T11:10:40.7309826Z 2: exit
```

**Comment by jwhui** [comment]
Another example.

Full log archive: [logs_5710.zip](https://github.com/openthread/openthread/files/4712237/logs_5710.zip)

Log snippet:
```
2020-06-01T15:53:44.5136090Z [0;32mPASS[0m tests/scripts/thread-cert/v1_2_router_5_1_1.py
2020-06-01T15:53:51.0385113Z [0;32mPASS[0m tests/scripts/thread-cert/v1_2_test_backbone_router_service.py
2020-06-01T15:54:09.8304043Z [0;31mFAIL[0m tests/scripts/thread-cert/v1_2_test_enhanced_frame_pending.py
2020-06-01T15:54:13.9543831Z [0;32mPASS[0m tests/scripts/thread-cert/v1_2_test_enhanced_keep_alive.py
2020-06-01T15:54:17.6053603Z [0;32mPASS[0m tests/scripts/thread-cert/v1_2_test_multicast_registration.py
2020-06-01T15:54:20.5348953Z [0;32mPASS[0m tests/scripts/thread-cert/v1_2_test_parent_selection.py
2020-06-01T15:54:20.5349867Z ==================================
2020-06-01T15:54:20.5350544Z          Test Summary
2020-06-01T15:54:20.5350883Z ==================================
2020-06-01T15:54:20.5351193Z # TOTAL: 6
2020-06-01T15:54:20.5351506Z # PASS: 5
2020-06-01T15:54:20.5351802Z # FAIL: 1
2020-06-01T15:54:20.5360080Z ==============================
2020-06-01T15:54:20.5361465Z !!! FAIL:tests/scripts/thread-cert/v1_2_test_enhanced_frame_pending.py
2020-06-01T15:54:20.5361662Z ==============================
2020-06-01T15:54:20.5362017Z /home/runner/work/openthread/openthread/build/cmake/openthread-simulation-1.2/examples/apps/cli/ot-cli-ftd 1
2020-06-01T15:54:20.5362150Z 1: extpanid 000db80000000000
2020-06-01T15:54:20.5362257Z 1: panid 64206
2020-06-01T15:54:20.5362340Z 1: mode rsdn
2020-06-01T15:54:20.5362872Z /home/runner/work/openthread/openthread/build/cmake/openthread-simulation-1.2/examples/apps/cli/ot-cli-ftd 2
2020-06-01T15:54:20.5363004Z 2: extpanid 000db80000000000
2020-06-01T15:54:20.5363112Z 2: panid 64206
2020-06-01T15:54:20.5363195Z 2: mode s
2020-06-01T15:54:20.5363294Z 2: childtimeout 30
2020-06-01T15:54:20.5363392Z 1: ifconfig up
2020-06-01T15:54:20.5363490Z 1: thread start
2020-06-01T15:54:20.5363571Z 1: state
2020-06-01T15:54:20.5363666Z 2: ifconfig up
2020-06-01T15:54:20.5363762Z 2: thread start
2020-06-01T15:54:20.5363864Z ActiveOperationalDataset is not implemented yet.
2020-06-01T15:54:20.5363953Z 2: state
2020-06-01T15:54:20.5364280Z 1: udp open
2020-06-01T15:54:20.5368142Z 1: udp bind :: 12345
2020-06-01T15:54:20.5368253Z 2: udp open
2020-06-01T15:54:20.5368585Z 2: udp bind :: 12345
2020-06-01T15:54:20.5368685Z 1: ipaddr rloc
2020-06-01T15:54:20.5368788Z 2: ping fd00:db8:0:0:0:ff:fe00:0
2020-06-01T15:54:20.5368889Z 2: ipaddr rloc
2020-06-01T15:54:20.5369280Z 1: udp send fd00:db8:0:0:0:ff:fe00:1 12345 -s 73 
2020-06-01T15:54:20.5369387Z 1: ipaddr rloc
2020-06-01T15:54:20.5369655Z 2: udp send fd00:db8:0:0:0:ff:fe00:0 12345 -s 73 
2020-06-01T15:54:20.5369761Z 1: thread stop
2020-06-01T15:54:20.5369853Z 1: ifconfig down
2020-06-01T15:54:20.5369949Z E
2020-06-01T15:54:20.5370052Z ======================================================================
2020-06-01T15:54:20.5370165Z ERROR: test (__main__.SED_EnhancedFramePending)
2020-06-01T15:54:20.5370436Z ----------------------------------------------------------------------
2020-06-01T15:54:20.5370548Z Traceback (most recent call last):
2020-06-01T15:54:20.5370891Z   File "/home/runner/work/openthread/openthread/tests/scripts/thread-cert/thread_cert.py", line 164, in tearDown
2020-06-01T15:54:20.5371014Z     node.destroy()
2020-06-01T15:54:20.5371317Z   File "/home/runner/work/openthread/openthread/tests/scripts/thread-cert/node.py", line 303, in destroy
2020-06-01T15:54:20.5371435Z     self.pexpect.expect(pexpect.EOF)
2020-06-01T15:54:20.5371749Z   File "/home/runner/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 344, in expect
2020-06-01T15:54:20.5371866Z     timeout, searchwindowsize, async_)
2020-06-01T15:54:20.5372326Z   File "/home/runner/.local/lib/python3.6/site-packages/pexpect/spawnbase.py", line 372, in expect_list
2020-06-01T15:54:20.5372461Z     return exp.expect_loop(timeout)
2020-06-01T15:54:20.5372818Z   File "/home/runner/.local/lib/python3.6/site-packages/pexpect/expect.py", line 181, in expect_loop
2020-06-01T15:54:20.5372937Z     return self.timeout(e)
2020-06-01T15:54:20.5373252Z   File "/home/runner/.local/lib/python3.6/site-packages/pexpect/expect.py", line 144, in timeout
2020-06-01T15:54:20.5373359Z     raise exc
2020-06-01T15:54:20.5373471Z pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7fdf783cf978>
2020-06-01T15:54:20.5373588Z searcher: searcher_re:
2020-06-01T15:54:20.5373686Z     0: EOF
2020-06-01T15:54:20.5373772Z <pexpect.popen_spawn.PopenSpawn object at 0x7fdf783cf978>
2020-06-01T15:54:20.5373878Z searcher: searcher_re:
2020-06-01T15:54:20.5373977Z     0: EOF
2020-06-01T15:54:20.5374025Z 
2020-06-01T15:54:20.5374312Z ----------------------------------------------------------------------
2020-06-01T15:54:20.5374422Z Ran 1 test in 10.588s
2020-06-01T15:54:20.5374471Z 
2020-06-01T15:54:20.5374566Z FAILED (errors=1)
2020-06-01T15:54:20.5374665Z 1: exit
```

**Comment by jwhui** [comment]
@librasungirl @bukepo , I'm seeing Thread 1.2 simulation tests fail very frequently. Thoughts on the issue or how to address?
