### ISSUE TITLE
[github-actions] OTCI cli-sim testCliSimRealTime fails intermittently

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#6461]
```
======================================================================
ERROR: testCliSimRealTime (__main__.TestOTCI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tools/otci/tests/test_otci.py", line 89, in testCliSimRealTime
    self._test_otci_single_node(node1)
  File "tools/otci/tests/test_otci.py", line 212, in _test_otci_single_node
    leader.set_backbone_router_config(seqno=bbr_config['seqno'] + 1, delay=10, timeout=301)
  File "/home/runner/.local/lib/python3.8/site-packages/otci_openthread-0.0.1-py3.8.egg/otci/otci.py", line 1587, in set_backbone_router_config
    self.execute_command(cmd)
  File "/home/runner/.local/lib/python3.8/site-packages/otci_openthread-0.0.1-py3.8.egg/otci/otci.py", line 115, in execute_command
    raise CommandError(cmd, output)
otci.errors.CommandError: Command error while executing 'bbr config seqno 256 delay 10 timeout 301':
Error 7: InvalidArgs
```

[logs_68963.zip](https://github.com/openthread/openthread/files/6321890/logs_68963.zip)

**Comment by simonlingoogle** [comment]
I guess `seqno 256` is invalid. should round it to 0.
