### ISSUE TITLE
I have installed pyrebase , When i try to executed  , I got this from terminal

### ISSUE THREAD

**Issue by rajcomputer-dwd** [openthread/openthread#6971]
C:\Users\Naveen\AppData\Local\Programs\Python\Python39\python.exe C:/Users/Naveen/PycharmProjects/pythonProject1/main.py
Traceback (most recent call last):
  File "C:\Users\Naveen\PycharmProjects\pythonProject1\main.py", line 1, in <module>
    from pyrebase import pyrebase
  File "C:\Users\Naveen\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrebase\__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "C:\Users\Naveen\AppData\Local\Programs\Python\Python39\lib\site-packages\pyrebase\pyrebase.py", line 23, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'

**Comment by jwhui** [comment]
This seems similar to #1137. Have you worked through those comments?

**Comment by rajcomputer-dwd** [comment]
I have tried pip install pycryptodome==3.4.3
 but it is not able to install , in terminal it shows like this 
Running setup.py install for pycryptodome ... error

**Comment by rdxpt** [comment]
@rajcomputer-dwd is there any other stack trace that you can share? Not sure if I can help, but I have been able to install `pycryptodome`, only getting the dist info details for it and not the sources itself.

**Comment by jwhui** [comment]
Closing stale issue.
