### ISSUE TITLE
[github-actions] test_ndproxy.py fails intermittently

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#7051]
```
======================================================================
ERROR: test (__main__.TestNdProxy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/openthread/openthread/tests/scripts/thread-cert/thread_cert.py", line 282, in tearDown
    self._verify_packets(test_info_path)
  File "/home/runner/work/openthread/openthread/tests/scripts/thread-cert/thread_cert.py", line 310, in _verify_packets
    self.verify(pv)
  File "./tests/scripts/thread-cert/backbone/test_ndproxy.py", line 141, in verify
    PBBR_DUA = pv.vars['PBBR_DUA']
KeyError: 'PBBR_DUA'

======================================================================
FAIL: test (__main__.TestNdProxy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/scripts/thread-cert/backbone/test_ndproxy.py", line 100, in test
    self.assertIsNotNone(self.nodes[PBBR].get_ip6_address(config.ADDRESS_TYPE.DUA))
AssertionError: unexpectedly None

----------------------------------------------------------------------
```

[logs_97399.zip](https://github.com/openthread/openthread/files/7254811/logs_97399.zip)
[thread-1-2-backbone-results.zip](https://github.com/openthread/openthread/files/7254812/thread-1-2-backbone-results.zip)

**Comment by jwhui** [comment]
Closing stale issue.
