### ISSUE TITLE
[github-actions] test_publish_meshcop_service.py fails consistently

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#7200]
```
======================================================================
FAIL: test (__main__.PublishMeshCopService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py", line 92, in test
    self.check_meshcop_service(br1, host)
  File "./tests/scripts/thread-cert/border_router/test_publish_meshcop_service.py", line 138, in check_meshcop_service
    self.fail('MeshCoP service not found')
AssertionError: MeshCoP service not found
----------------------------------------------------------------------
```

[logs_104913.zip](https://github.com/openthread/openthread/files/7597987/logs_104913.zip)
[thread-border-router-results.zip](https://github.com/openthread/openthread/files/7597990/thread-border-router-results.zip)

**Comment by jwhui** [comment]
All recently submitted PRs are failing on this test.
