### ISSUE TITLE
[github-actions] test_dua_routing_med.py fails intermittently

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#7403]
```
======================================================================
ERROR: test (__main__.TestDuaRoutingMed)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/openthread/openthread/tests/scripts/thread-cert/thread_cert.py", line 302, in tearDown
    self._verify_packets(test_info_path)
  File "/home/runner/work/openthread/openthread/tests/scripts/thread-cert/thread_cert.py", line 330, in _verify_packets
    self.verify(pv)
  File "./tests/scripts/thread-cert/backbone/test_dua_routing_med.py", line 268, in verify
    ping_request_pkts.filter_wpan_src64(PBBR2).filter_ping_request(identifier=ping_id).must_next()
  File "/home/runner/work/openthread/openthread/tests/scripts/thread-cert/pktverify/packet_filter.py", line 233, in must_next
    raise errors.PacketNotFound(self.index, self._stop_index)
pktverify.errors.PacketNotFound: ((587, 595), (626, 626))

----------------------------------------------------------------------
```
[logs_113759.zip](https://github.com/openthread/openthread/files/8027523/logs_113759.zip)
[thread-1-2-backbone-results.zip](https://github.com/openthread/openthread/files/8027524/thread-1-2-backbone-results.zip)
https://github.com/openthread/openthread/runs/5114953523?check_suite_focus=true

**Comment by jwhui** [comment]
https://github.com/openthread/ot-br-posix/runs/5497668803?check_suite_focus=true

**Comment by jwhui** [comment]
Closing stale issue.
