### ISSUE TITLE
[github-actions] stress connectivity fails intermittently

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#7474]
```
Traceback (most recent call last):
**[OTNS](https://github.com/openthread/ot-ns) Stress Tests Report Generated at 03/10 15:07:23**
  File "/tmp/otns/pylibs/stress_tests/run_stress_suite.py", line 95, in <module>
    main()
  File "/tmp/otns/pylibs/stress_tests/run_stress_suite.py", line 70, in main
    run_suite(script_dir, suite_name)
  File "/tmp/otns/pylibs/stress_tests/run_stress_suite.py", line 91, in run_suite
    t.run(report=True)
  File "/tmp/otns/pylibs/stress_tests/BaseStressTest.py", line 60, in run_wrapper
    self.report()
  File "/tmp/otns/pylibs/stress_tests/BaseStressTest.py", line 120, in report
    raise RuntimeError("Stress test failed: \n" + "\n".join("\t" + msg for msg in self.result._fail_msgs))
RuntimeError: Stress test failed: 
	Max Delay (3780s)> 3600s
#### ML-EID Connectivity Test **Failed**: Max Delay (3780s)> 3600s _(03/10 14:58:35 ~ 03/10 15:07:23)_
| Simulation Time | Max Delay | Min Delay | Avg Delay |
| :-: | :-: | :-: | :-: |
| 6h | 3780s | 60s | 582s |
Error: Process completed with exit code 1.
```
https://github.com/openthread/openthread/runs/5497700124?check_suite_focus=true
[logs_116656.zip](https://github.com/openthread/openthread/files/8224597/logs_116656.zip)

**Comment by jwhui** [comment]
https://github.com/openthread/openthread/runs/5544983390?check_suite_focus=true

**Comment by jwhui** [comment]
https://github.com/openthread/openthread/runs/5670798418?check_suite_focus=true

**Comment by jwhui** [comment]
https://github.com/openthread/openthread/actions/runs/2921188897

**Comment by jwhui** [comment]
https://github.com/openthread/openthread/runs/8002441990?check_suite_focus=true

**Comment by simonlingoogle** [comment]
This has been a long outstanding failure. 
The test fails when one (or more) SED failed to ping the BR within 3600 seconds. 
Will take a look.

**Comment by EskoDijk** [comment]
Updates to the test were made in https://github.com/EskoDijk/ot-ns/blob/main/pylibs/stress_tests/mleid_connectivity.py to address sporadic failure and to add more documentation. Maybe we can resolve this by including OTNS2 in the openthread CI, to be discussed further in April.

**Comment by zesonzhang** [comment]
I also see the similar issue happened in my PR
```
2024-08-02 09:00:36,124 - DEBUG - _last_ping_succ_time {1: 21540, 44: 21240, 34: 21240, 28: 21180, 30: 21180, 40: 19500, 24: 21240, 6: 21240, 49: 21180, 2: 21240, 48: 21240, 14: 21240, 45: 21180, 39: 21240, 9: 21240, 5: 21180, 50: 21180, 13: 21180, 19: 17580, 25: 21240, 16: 21240, 10: 21240, 3: 21240, 8: 21240, 36: 21180, 43: 21240, 32: 21180, 41: 21240, 31: 21240, 21: 21060, 26: 21240, 23: 21060, 18: 21240, 17: 21180, 4: 21000, 12: 21240, 42: 21240, 47: 21240, 27: 21240, 46: 21240, 22: 21180, 15: 21240, 20: 21180, 29: 21180, 7: 21060, 35: 21240, 11: 21240, 38: 21240, 37: 21180, 33: 21240} delays [60, 360, 360, 600, 420, 360, 540, 360, 360, 360, 360, 360, 420, 360, 360, 360, 420, 360, 4020, 420, 540, 420, 540, 360, 360, 360, 360, 420, 420, 420, 360, 420, 360, 360, 360, 420, 420, 360, 360, 2100, 360, 360, 360, 360, 420, 360, 360, 360, 420, 420]
2024-08-02 09:00:36,124 - INFO - waiting for OTNS to close ...
**[OTNS](https://github.com/openthread/ot-ns) Stress Tests Report Generated at 08/02 08:54:15**
#### ML-EID Connectivity Test **Passed** _(08/02 08:46:48 ~ 08/02 08:54:14)_
| Simulation Time | Max Delay | Min Delay | Avg Delay |
| :-: | :-: | :-: | :-: |
| 6h | 660s | 60s | 170s |
**[OTNS](https://github.com/openthread/ot-ns) Stress Tests Report Generated at 08/02 09:00:37**
#### Service Connectivity Test **Failed**: Max Delay (4020s)> 3600s _(08/02 08:54:15 ~ 08/02 09:00:36)_
| Simulation Time | Max Delay | Min Delay | Avg Delay |
| :-: | :-: | :-: | :-: |
| 6h | 4020s | 60s | 494s |
Traceback (most recent call last):
  File "/tmp/otns/pylibs/stress_tests/run_stress_suite.py", line 95, in <module>
    main()
  File "/tmp/otns/pylibs/stress_tests/run_stress_suite.py", line 70, in main
    run_suite(script_dir, suite_name)
  File "/tmp/otns/pylibs/stress_tests/run_stress_suite.py", line 91, in run_suite
    t.run(report=True)
  File "/tmp/otns/pylibs/stress_tests/BaseStressTest.py", line 60, in run_wrapper
    self.report()
  File "/tmp/otns/pylibs/stress_tests/BaseStressTest.py", line 120, in report
    raise RuntimeError("Stress test failed: \n" + "\n".join("\t" + msg for msg in self.result._fail_msgs))
RuntimeError: Stress test failed: 
	Max Delay (4020s)> 3600s
Error: Process completed with exit code 1.
```

https://github.com/openthread/openthread/actions/runs/10212705852/job/28256588889?pr=10574

**Comment by EskoDijk** [comment]
The OTNS v2 has a solution to such random failures - it can run tests with deterministic pseudo-random generators in simulation and on simulated nodes as well. This has already worked for sone random test failure cases I experienced. Perhaps we should soon start the process to integrate OTNS v2, @jwhui ? :)

**Comment by jwhui** [comment]
> The OTNS v2 has a solution to such random failures - it can run tests with deterministic pseudo-random generators in simulation and on simulated nodes as well. This has already worked for sone random test failure cases I experienced. Perhaps we should soon start the process to integrate OTNS v2, @jwhui ? :)

Yes, let's do it, @EskoDijk !

**Comment by EskoDijk** [comment]
@jwhui This issue can be closed now, I think. Haven't seen this fail, recently.
