### ISSUE TITLE
Can't start launch_testbed.py for harness-simulation

### ISSUE THREAD

**Issue by lboue** [openthread/openthread#8087]
**Can't start launch_testbed.py for harness-simulation**
ImportError: cannot import name 'sniffer_pb2' from 'proto' (unknown location)

**To Reproduce**:

1. git clone https://github.com/openthread/openthread.git
2. cd openthread/
3. CFLAGS='-DOPENTHREAD_CONFIG_IP6_MAX_EXT_MCAST_ADDRS=8' \\
  CXXFLAGS='-DOPENTHREAD_CONFIG_IP6_MAX_EXT_MCAST_ADDRS=8' \\
  script/cmake-build simulation \\
      -DOT_THREAD_VERSION=1.2 \\
      -DOT_DUA=ON \\
      -DOT_MLR=ON \\
      -DOT_COMMISSIONER=ON \\
      -DOT_CSL_RECEIVER=ON \\
      -DOT_SIMULATION_MAX_NETWORK_SIZE=64
5. cd /home/user/openthread/tools/harness-simulation/posix/
6. OT_PATH=/home/user/openthread ./build_docker_image.sh
7. pip install -r requirements.txt
8. tools/harness-simulation/posix/install.sh
9. python3 launch_testbed.py \
    --interface=ens33     \
    --ot=6                \
    --otbr=4              \
    --sniffer=2

**Start harness-simulation**

**Console/log output** 
```
user@ubuntu:~/openthread/tools/harness-simulation/posix$ sudo python3 launch_testbed.py     --interface=ens33         --ot=6                    --otbr=4                  --sniffer=2
INFO:root:Executing command:  python3 sniffer_sim/sniffer.py --grpc-server 192.168.1.185:50051
INFO:root:Executing command:  python3 sniffer_sim/sniffer.py --grpc-server 192.168.1.185:50052
INFO:otbr_docker.OtbrDocker:Launching OTBR<7> ...
Traceback (most recent call last):
  File "launch_testbed.py", line 247, in <module>
    main()
  File "launch_testbed.py", line 202, in main
    otbr_dockers.append(otbr_docker.OtbrDocker(nodeid, OTBR_DOCKER_NAME_PREFIX + str(nodeid)))
  File "/home/user/openthread/tools/harness-simulation/posix/otbr_sim/otbr_docker.py", line 55, in __init__
    self._launch()
  File "/home/user/openthread/tools/harness-simulation/posix/otbr_sim/otbr_docker.py", line 62, in _launch
    self._launch_socat()
  File "/home/user/openthread/tools/harness-simulation/posix/otbr_sim/otbr_docker.py", line 75, in _launch_socat
    self._socat_proc = subprocess.Popen(['socat', '-d', '-d', 'pty,raw,echo=0', 'pty,raw,echo=0'],
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'socat'
user@ubuntu:~/openthread/tools/harness-simulation/posix$ Traceback (most recent call last):
  File "sniffer_sim/sniffer.py", line 43, in <module>
    from proto import sniffer_pb2
ImportError: cannot import name 'sniffer_pb2' from 'proto' (unknown location)
Traceback (most recent call last):
  File "sniffer_sim/sniffer.py", line 43, in <module>
    from proto import sniffer_pb2
ImportError: cannot import name 'sniffer_pb2' from 'proto' (unknown location)
```

**Comment by jwhui** [comment]
@lboue , do you have `socat` installed?

If not, try the following:
```
sudo apt-get update
sudo apt-get install socat
```
